CREATE TABLE aspect
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_aspect PRIMARY KEY (id)
);

CREATE TABLE aspect_collection
(
    aspect_id     INTEGER NOT NULL,
    collection_id INTEGER NOT NULL
);

CREATE TABLE aspect_data_resource
(
    aspect_id        INTEGER NOT NULL,
    data_resource_id INTEGER NOT NULL
);

CREATE TABLE aspect_steppers
(
    aspect_id       INTEGER NOT NULL,
    stepper_step_id INTEGER NOT NULL
);

CREATE TABLE collection
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_collection PRIMARY KEY (id)
);

CREATE TABLE data_resource
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    type VARCHAR(255),
    CONSTRAINT pk_data_resource PRIMARY KEY (id)
);

CREATE TABLE stepper_step
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stepper_tag      INTEGER,
    stepper_index    INTEGER,
    data_resource_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_stepper_step PRIMARY KEY (id)
);

ALTER TABLE stepper_step
    ADD CONSTRAINT FK_STEPPER_STEP_ON_DATA_RESOURCE FOREIGN KEY (data_resource_id) REFERENCES data_resource (id);

ALTER TABLE aspect_collection
    ADD CONSTRAINT fk_aspcol_on_aspect FOREIGN KEY (aspect_id) REFERENCES aspect (id);

ALTER TABLE aspect_collection
    ADD CONSTRAINT fk_aspcol_on_aspect_collection FOREIGN KEY (collection_id) REFERENCES collection (id);

ALTER TABLE aspect_data_resource
    ADD CONSTRAINT fk_aspdatres_on_aspect FOREIGN KEY (aspect_id) REFERENCES aspect (id);

ALTER TABLE aspect_data_resource
    ADD CONSTRAINT fk_aspdatres_on_data_resource FOREIGN KEY (data_resource_id) REFERENCES data_resource (id);

ALTER TABLE aspect_steppers
    ADD CONSTRAINT fk_aspste_on_aspect FOREIGN KEY (aspect_id) REFERENCES aspect (id);

ALTER TABLE aspect_steppers
    ADD CONSTRAINT fk_aspste_on_stepper_step FOREIGN KEY (stepper_step_id) REFERENCES stepper_step (id);